support/mkbundle: switch from distutils to setuptools
Fixes build error with python-3.12:

Traceback (most recent call last):
  File "support/mkbundle", line 48, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils'

Signed-off-by: Bernd Kuhls <bernd@kuhls.net>