Add missing include for kill(2)
src/spawn.c:306:7: warning: implicit declaration of function 'kill' is invalid in C99 [-Wimplicit-function-declaration]
      kill(-(s->pid), SIGKILL);
      ^
src/spawn.c:306:23: error: use of undeclared identifier 'SIGKILL'
      kill(-(s->pid), SIGKILL);
                      ^
src/spawn.c:655:3: warning: implicit declaration of function 'pthread_kill' is invalid in C99
      [-Wimplicit-function-declaration]
  pthread_kill(spawn_pipe_tid, SIGTERM);
  ^
src/spawn.c:655:32: error: use of undeclared identifier 'SIGTERM'
pthread_kill(spawn_pipe_tid, SIGTERM);