Add missing include for accept(2) on FreeBSD.
tvheadend-3.4/src/epggrab/module.c: In function '_epggrab_socket_thread':
tvheadend-3.4/src/epggrab/module.c:357: warning: implicit declaration of function 'accept'
tvheadend-3.4/src/epggrab/module.c: In function 'epggrab_module_enable_socket':
tvheadend-3.4/src/epggrab/module.c:382: warning: implicit declaration of function 'shutdown'
tvheadend-3.4/src/epggrab/module.c:382: error: 'SHUT_RDWR' undeclared (first use in this function)
tvheadend-3.4/src/epggrab/module.c:382: error: (Each undeclared identifier is reported only once
tvheadend-3.4/src/epggrab/module.c:382: error: for each function it appears in.)
tvheadend-3.4/src/epggrab/module.c:392: warning: implicit declaration of function 'socket'
tvheadend-3.4/src/epggrab/module.c:392: error: 'AF_UNIX' undeclared (first use in this function)
tvheadend-3.4/src/epggrab/module.c:392: error: 'SOCK_STREAM' undeclared (first use in this function)
tvheadend-3.4/src/epggrab/module.c:398: warning: implicit declaration of function 'bind'
tvheadend-3.4/src/epggrab/module.c:406: warning: implicit declaration of function 'listen'