Add missing include for FreeBSD which has AF_INET6 defined in sys/socket.h
tvheadend-3.4/src/access.c: In function 'netmask_verify':
tvheadend-3.4/src/access.c:164: error: dereferencing pointer to incomplete type
tvheadend-3.4/src/access.c:164: error: 'AF_INET6' undeclared (first use in this function)
tvheadend-3.4/src/access.c:164: error: (Each undeclared identifier is reported only once
tvheadend-3.4/src/access.c:164: error: for each function it appears in.)
tvheadend-3.4/src/access.c:177: error: dereferencing pointer to incomplete type
tvheadend-3.4/src/access.c:177: error: 'AF_INET' undeclared (first use in this function)
tvheadend-3.4/src/access.c:193: error: dereferencing pointer to incomplete type
tvheadend-3.4/src/access.c: In function 'access_set_prefix':
tvheadend-3.4/src/access.c:422: error: 'AF_INET6' undeclared (first use in this function)
tvheadend-3.4/src/access.c: In function 'access_record_build':
tvheadend-3.4/src/access.c:554: error: 'AF_INET6' undeclared (first use in this function)