Add missing include for FreeBSD which has AF_INET and AF_INET6 defined in sys/socket.h
tvheadend-3.4/src/webui/extjs.c: In function 'service_update_iptv':
tvheadend-3.4/src/webui/extjs.c:1748: error: 'AF_INET' undeclared (first use in this function)
tvheadend-3.4/src/webui/extjs.c:1748: error: (Each undeclared identifier is reported only once
tvheadend-3.4/src/webui/extjs.c:1748: error: for each function it appears in.)
tvheadend-3.4/src/webui/extjs.c:1749: error: 'AF_INET6' undeclared (first use in this function)
tvheadend-3.4/src/webui/extjs.c: In function 'build_record_iptv':
tvheadend-3.4/src/webui/extjs.c:1776: error: 'AF_INET' undeclared (first use in this function)
tvheadend-3.4/src/webui/extjs.c:1780: error: 'AF_INET6' undeclared (first use in this function)