Add missing includes for shutdown(2) and SHUT_RDWR on FreeBSD.
tvheadend-3.4/src/cwc.c: In function 'cwc_session':
tvheadend-3.4/src/cwc.c:1139: warning: implicit declaration of function 'shutdown'
tvheadend-3.4/src/cwc.c:1139: error: 'SHUT_RDWR' undeclared (first use in this function)
tvheadend-3.4/src/cwc.c:1139: error: (Each undeclared identifier is reported only once
tvheadend-3.4/src/cwc.c:1139: error: for each function it appears in.)
tvheadend-3.4/src/cwc.c: In function 'cwc_entry_update':
tvheadend-3.4/src/cwc.c:2369: error: 'SHUT_RDWR' undeclared